main:
	g++ -c LevelStrategy.cpp -o LevelStrategy.o
	g++ -c PerformStrategy.cpp -o PerformStrategy.o
	g++ -c Calculator.cpp -o Calculator.o
	g++ -c main.cpp -o main.o
	g++ LevelStrategy.o PerformStrategy.o Calculator.o main.o -o main